### ISSUE TITLE
Version checks break down

### ISSUE THREAD

**Issue by lynnard** [pebbe/zmq3#22]
The new commit b7635c670c63b0e303f1b98029d1f74614bf6e6b breaks my program. It keeps complaining that my major version is 4 although it is really 3

**Comment by pebbe** [comment]
That can't be. Are you on Linux? What does `ldd` show for library version?

**Comment by lynnard** [comment]
Sorry I think it was a problem with Ubuntu's libzmq3 package... A simple version checker in c tells me my system is using zeromq 4.0.4. Uninstalled Ubuntu's version and compiled from source for zmq3; seems to work now..
