### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by scragg0x** [pebbe/zmq3#23]
I get the following when trying to get the zmq3 package.  I am running ubuntu 14.04 and installed `libzmq3-dev` and also tried compiling from source.  I run `ldconfig`  for good measure, still the same error.

$ go get github.com/pebbe/zmq3

In file included from src/github.com/pebbe/zmq3/errors.go:5:0:
zmq3.h:2:2: error: #error "You need ZeroMQ version 3 to build this"
 #error "You need ZeroMQ version 3 to build this"

**Comment by pebbe** [comment]
Try this:

    pkg-config --modversion libzmq

What does it say?

**Comment by scragg0x** [comment]
@pebbe 3.2.5

**Comment by scragg0x** [comment]
n/m I had a compiled version4 in usr/local/include and just deleted that zmq.h

**Comment by pebbe** [comment]
So, is it working now?

**Comment by scragg0x** [comment]
yes
