### ISSUE TITLE
Maybe struct Poller needs a unregister/remove function

### ISSUE THREAD

**Issue by lorneli** [pebbe/zmq3#24]
Hi, I think maybe struct Poller needs a unregister/remove function.  I have found a [python version unregister funcion](https://github.com/zeromq/pyzmq/blob/550ddc04c3ce67cdb58b6fb6499274dc7f82891c/zmq/sugar/poll.py#L63) for poller.

Without this function, I use `poller.UpdateBySocket(zmqSocket, 0)` alternatively, which disables this socket by bitmask but not removes it. This may cause socks and items in Poller growing larger and larger when application runs.

Thanks.

**Comment by pebbe** [comment]
I added Poller.Remove and Poller.RemoveBySocket

**Comment by lorneli** [comment]
Thanks a lot.
